#!/usr/bin/env bash

# load-env.sh Resolve local environment variables and write .env to project root
#
# Usage (via just):
#   just load-env
#
# The script merges variables from:
#   1. .devcontainer/configs/.env.local  (project-specific, committed to git)
#   2. Variables generated by this script (dynamic/resolved at runtime)
#
# The result is written to .env at the project root. Every justfile loads
# that .env automatically via dotenv-path.
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
CONFIGS_DIR="${SCRIPT_DIR}/../configs"
ENV_LOCAL="${CONFIGS_DIR}/.env.local"
ENV_FILE="${PROJECT_ROOT}/.env"

# Start with header
cat > "${ENV_FILE}" <<EOF
# Auto-generated by .devcontainer/scripts/load-env.sh
# Do not edit manually, re-generate with: just load-env
EOF

# Append .env.local if it exists
if [[ -f "${ENV_LOCAL}" ]]; then
  echo "" >> "${ENV_FILE}"
  echo "# ── From .devcontainer/configs/.env.local ─────────────────────────────────" >> "${ENV_FILE}"
  cat "${ENV_LOCAL}" >> "${ENV_FILE}"
fi

# Append script-generated variables
echo "" >> "${ENV_FILE}"
echo "# ── Generated by load-env.sh ───────────────────────────────────────────────" >> "${ENV_FILE}"
